name: Build and Deploy Docker Container

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: expressazureterraform.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: expressazureterraform.azurecr.io/myimage:${{ github.sha }}

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.4.2
         
      - name: Terraform Init
        run: terraform init -backend-config="client_id=${{secrets.CLIENT_ID}}" -backend-config="client_secret=${{secrets.CLIENT_SECRET}}" -backend-config="subscription_id=${{secrets.SUBSCRIPTION_ID}}"
     
      - name: Terraform plan
        run: | 
          export TF_VAR_ACR_USERNAME=${{secrets.ACR_USERNAME}}
          export TF_VAR_ACR_PASSWORD=${{secrets.ACR_PASSWORD}}
          export TF_VAR_SUBSCRIPTION_ID=${{secrets.SUBSCRIPTION_ID}}
          export TF_VAR_TENANT_ID=${{secrets.TENANT_ID}}
          export TF_VAR_LOCATION=${{secrets.LOCATION}}
          export TF_VAR_IMAGE_SERVER=${{secrets.IMAGE_SERVER}}
          export TF_VAR_CLIENT_ID=${{secrets.CLIENT_ID}}
          export TF_VAR_CLIENT_SECRET=${{secrets.CLIENT_SECRET}}
          export TF_VAR_CONTAINER_IMAGE=expressazureterraform.azurecr.io/myimage:${{ github.sha }}
          terraform plan -out=plan.tfplan  -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: | 
          export TF_VAR_ACR_USERNAME=${{secrets.ACR_USERNAME}}
          export TF_VAR_ACR_PASSWORD=${{secrets.ACR_PASSWORD}}
          export TF_VAR_SUBSCRIPTION_ID=${{secrets.SUBSCRIPTION_ID}}
          export TF_VAR_TENANT_ID=${{secrets.TENANT_ID}}
          export TF_VAR_LOCATION=${{secrets.LOCATION}}
          export TF_VAR_IMAGE_SERVER=${{secrets.IMAGE_SERVER}}
          export TF_VAR_CLIENT_ID=${{secrets.CLIENT_ID}}
          export TF_VAR_CLIENT_SECRET=${{secrets.CLIENT_SECRET}}
          export TF_VAR_CONTAINER_IMAGE=expressazureterraform.azurecr.io/myimage:${{ github.sha }}
          terraform apply -auto-approve -input=false

